## Big Data Analysis Project - Weather

In this I have performed Data Analysis and processing using Pandas and Python.

The Project uses the weather dataset from https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/by_year/.

This project will use only 3 years of data ( 2015 - 2018) for all the stations starting with US and
elements TMAX(Maximum temperature), TMIN(Minimum temperature).

We only need data corresponding to TMAX and TMIN.
1st step is to download the given data which can be done using this linux script.

This is the script:
for i in `seq 2015 2018`

wget https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/by_year/${i}.csv.gz

gzip -cd ${i}.csv.gz | grep -e TMIN -e TMAX | grep ^US > ${i}.csv 

It can be seen as only the data corresponding to TMIN and TMAX is needed we dowload only those datasets.


for explanation of ELEMENT codes and their units as well as the M-FLAG, Q-FLAGS and S-FLAGS.

ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt file

### Maximum TMAX, Minimum TMIN for each year excluding abnormalities or missing data

In [17]:

import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
#After downloading the data we need to append all files of 2015-2018 into one file , myl is an empty list
# all the data for 3 years is appended to it
myl = []
for year in range(5,8):
     myl.append(pd.read_csv(f'201{year}.csv', sep = ',', header=None))
fullframe = pd.concat(myl)

Here all the basic operations on the data so as to remove all the points which are abnormal or missing , setting column names etc.

In [9]:

#setting column names
fullframe.columns = ['St' , 'Date' , 'Attribute' , 'Value' , 'Mflag' , 'Qflag' , 'Sflag' , 'Unknown']


#To distinguish the data on the basis of Year because I need a yearly analysis so I have generated 
# a year column from the given date.
fullframe['Year'] = fullframe['Date']//10000
#The values are in Celcius but they till the 1st decimal place so we have to divide by 10 so that they are in correct format
fullframe['Value'] = fullframe['Value'] /10


#In order to check whether the data is valid a no. of tests were performed. One of them was the Q-Flag
#Q-Flag character Quality Flag , understanding the data I found out that if the Q-flag value was empty
# then the data was correct otherwise it had some quality problem. 
#So first all the Nan were replaced with ''.Only those data were taken where Q-flag test was fulfilled
fullframe.fillna('', inplace = True)

#filtering the data which failed Q Flag test
fullframe = fullframe[fullframe['Qflag'] == '']

## The DataSet

In [19]:
fullframe

,St,Date,Attribute,Value,Mflag,Qflag,Sflag,Unknown,Year
0,USW00094626,20150101,TMAX,-6.0,,,W,,2015
1,USW00094626,20150101,TMIN,-14.3,,,W,,2015
2,USW00003048,20150101,TMAX,0.8,,,R,,2015
3,USW00003048,20150101,TMIN,-7.6,,,R,,2015
4,USW00024229,20150101,TMAX,3.9,,,W,2400,2015
5,USW00024229,20150101,TMIN,-4.3,,,W,2400,2015
6,USW00003889,20150101,TMAX,2.8,,,W,700,2015
7,USW00003889,20150101,TMIN,-6.0,,,W,700,2015
8,USW00003967,20150101,TMAX,1.1,,,W,,2015
9,USW00003967,20150101,TMIN,-8.8,,,W,,2015
10,USW00004131,20150101,TMAX,-16.4,,,R,,2015
11,USW00004131,20150101,TMIN,-31.1,,,R,,2015
12,USW00012842,20150101,TMAX,23.3,,,W,2400,2015
13,USW00012842,20150101,TMIN,15.0,,,W,2400,2015
14,USW00012876,20150101,TMAX,23.9,,,W,,2015
15,USW00012876,20150101,TMIN,15.0,,,W,,2015
16,USW00014719,20150101,TMAX,4.4,,,W,,2015
17,USW00014719,20150101,TMIN,-11.6,,,W,,2015
18,USW00024061,20150101,TMAX,-14.9,,,W,,2015
19,USW00024061,20150101,TMIN,-27.1,,,W,,2015
20,USS0019L03S,20150101,TMAX,4.7,,,T,,2015
21,USS0019L03S,20150101,TMIN,-13.9,,,T,,2015
22,USS0018F01S,20150101,TMAX,-1.7,,,T,,2015
23,USS0018F01S,20150101,TMIN,-16.9,,,T,,2015
24,USS0017B04S,20150101,TMAX,-9.4,,,T,,2015
25,USS0017B04S,20150101,TMIN,-13.8,,,T,,2015
26,USS0014G01S,20150101,TMAX,-4.0,,,T,,2015
27,USS0014G01S,20150101,TMIN,-13.9,,,T,,2015
28,USS0014C04S,20150101,TMAX,-7.4,,,T,,2015
29,USS0014C04S,20150101,TMIN,-15.3,,,T,,2015
...,...,...,...,...,...,...,...,...,...
5625204,USC00010583,20171231,TMIN,-0.6,,,7,700,2017
5625205,USC00025825,20171231,TMAX,17.2,,,7,1600,2017
5625206,USC00025825,20171231,TMIN,-1.7,,,7,1600,2017
5625207,USC00354622,20171231,TMAX,4.4,,,7,800,2017
5625208,USC00354622,20171231,TMIN,-7.2,,,7,800,2017
5625209,USC00353522,20171231,TMAX,6.1,,,7,800,2017
5625210,USC00353522,20171231,TMIN,0.6,,,7,800,2017
5625211,USC00344236,20171231,TMAX,-4.4,,,7,2400,2017
5625212,USC00344236,20171231,TMIN,-11.1,,,7,2400,2017
5625213,USC00324083,20171231,TMAX,-27.2,,,7,700,2017
5625214,USC00324083,20171231,TMIN,-33.3,,,7,700,2017
5625215,USC00314987,20171231,TMAX,10.6,,,7,700,2017
5625216,USC00314987,20171231,TMIN,-10.0,,,7,700,2017
5625217,USC00309000,20171231,TMAX,-8.3,,,7,800,2017
5625218,USC00309000,20171231,TMIN,-27.8,,,7,800,2017
5625219,USC00304174,20171231,TMAX,-7.8,,,7,700,2017
5625220,USC00304174,20171231,TMIN,-17.2,,,7,700,2017
5625221,USC00299569,20171231,TMAX,11.7,,,7,2400,2017
5625222,USC00299569,20171231,TMIN,-7.8,,,7,2400,2017
5625223,USC00292100,20171231,TMAX,15.6,,,7,700,2017
5625224,USC00292100,20171231,TMIN,-8.3,,,7,700,2017
5625225,USC00148171,20171231,TMAX,-12.8,,,7,2400,2017
5625226,USC00148171,20171231,TMIN,-20.6,,,7,2400,2017
5625227,USC00130157,20171231,TMAX,-21.1,,,7,700,2017
5625228,USC00130157,20171231,TMIN,-23.3,,,7,700,2017
5625229,USC00103732,20171231,TMAX,-0.6,,,7,800,2017
5625230,USC00103732,20171231,TMIN,-13.9,,,7,800,2017
5625231,USC00094170,20171231,TMAX,13.9,,,7,800,2017
5625232,USC00094170,20171231,TMIN,-1.1,,,7,800,2017
5625233,USC00086092,20171231,TMIN,11.1,,,7,700,2017

In [34]:
#maximum temperature of each year with Qflag = ''
#As we have to find the maximum value of TMAX first all data is grouped by Year and Attribute then max value is found. 
#Pivot 
max_min_df=fullframe.groupby(['Year','Attribute'])['Value'].max().reset_index().pivot(index = 'Year' , columns= 'Attribute')

max_min_df.columns = max_min_df.columns.get_level_values(1)
#We only need the TMAX out of them because the TMIN value which is calculated is the maximum of the minimum temperatures 

max_min_df = max_min_df.loc[:,['TMAX']]


#minimum temperature of each year with Qflag = ''
#Similar to the above process first all data is grouped acc. to year and attribute , then min. value is found and data is pivoted
min_min_df=fullframe.groupby(['Year','Attribute'])['Value'].min().reset_index().pivot(index = 'Year' , columns= 'Attribute')
min_min_df.columns = min_min_df.columns.get_level_values(1)
min_min_df = min_min_df.loc[:,['TMIN']]

In [31]:
#We have calculated both the TMAX and TMIN now we just have to merge them on the basis of the year 
# first create a list with both dataframes and apply merge operation on them 
frames  = [max_min_df , min_min_df]
result  = pd.merge(max_min_df , min_min_df , on = 'Year')

result.reset_index()
result

After finding the maximum and minimum temperature of a place here I am finding the corresponding weather stations of the tempereatures

In [411]:
#merging fullframe with max_min_df to find the stations corresponding to max temperature
#For performing the merge operation on the max_min_df we need year and attribute(TMAX) and we need corresponding year and value
# in fullframe.
result_max = pd.merge(max_min_df , fullframe.loc[ fullframe.Attribute == 'TMAX',:] , left_on = ['Year','TMAX' ], right_on=['Year','Value'])

In [413]:
#result max has values occuring more than once so we use group by 
result_max
#corresponding Station for maximum temperature
result_max.groupby(['Year'])['TMAX','St'].max()

,Year,TMAX,St,Date,Attribute,Value,Mflag,Qflag,Sflag,Unknown
0,2015,556,USR0000HKAU,20150213,TMAX,556,H,,U,
1,2015,556,USR0000HKAU,20150215,TMAX,556,H,,U,
2,2016,539,USR0000CBEV,20160926,TMAX,539,H,,U,
3,2017,528,USC00042319,20170620,TMAX,528,,,7,2400
4,2017,528,USC00042319,20170624,TMAX,528,,,7,2400
5,2017,528,USC00042319,20170707,TMAX,528,,,7,2400
6,2017,528,USC00042319,20170801,TMAX,528,,,7,2400
7,2018,467,USC00042319,20180509,TMAX,467,,,H,2400

In [35]:
#merging fullframe with min_min_df to find the stations corresponding to min temperature
result_min = pd.merge(min_min_df , fullframe.loc[ fullframe.Attribute == 'TMIN',:] , left_on = ['Year','TMIN' ], right_on=['Year','Value'])
result_min.groupby(['Year'])['TMIN' , 'St'].min()

      TMIN           St
Year
2015 -52.8  USC00502339
2016 -46.9  USS0051R01S
2017 -52.0  USS0051R01S

## Average TMIN, TMAX for each year excluding abnormalities or missing data

In [39]:
avg_df = fullframe.groupby(['Year','Attribute'])['Value'].mean().reset_index().pivot(index = 'Year' , columns= 'Attribute')
avg_df.columns = avg_df.columns.get_level_values(1)
avg_df

Attribute       TMAX      TMIN
Year
2015       17.712354  5.343164
2016       17.899826  5.500843
2017       17.654745  5.267168

## 5 hottest , 5 coldest weather stations for each year excluding abnormalities or missing data

In [121]:
cold_df = fullframe.groupby('Year')['Value'].apply(lambda grp: grp.nsmallest(5)).reset_index().drop('level_1' , axis = 1)
cold_result = pd.merge( cold_df, fullframe.loc[ fullframe.Attribute == 'TMIN',:] , left_on = ['Year','Value' ], right_on=['Year','Value'])
cold_result.groupby('Year').apply(lambda grp: grp.nsmallest(5 , columns = 'Year'))

         Year  Value           St      Date Attribute Mflag Qflag Sflag  \
Year
2015 0   2015  -52.8  USC00502339  20150127      TMIN                 7
     1   2015  -51.1  USC00502339  20150208      TMIN                 7
     2   2015  -50.6  USC00501684  20150128      TMIN                 7
     3   2015  -50.6  USC00502339  20150207      TMIN                 7
     4   2015  -50.6  USC00501684  20150207      TMIN                 7
2016 14  2016  -46.9  USS0051R01S  20161130      TMIN                 T
     15  2016  -46.7  USR0000ACHL  20161207      TMIN     H           U
     16  2016  -46.7  USC00501684  20161210      TMIN                 7
     17  2016  -46.7  USR0000ACHL  20161207      TMIN     H           U
     18  2016  -46.7  USC00501684  20161210      TMIN                 7
2017 23  2017  -52.0  USS0051R01S  20170119      TMIN                 T
     24  2017  -50.6  USR0000ASLC  20170118      TMIN     H           U
     25  2017  -50.6  USW00026529  20170119      TMIN                 7
     26  2017  -50.6  USW00026529  20170120      TMIN                 7
     27  2017  -50.6  USR0000ASLC  20170118      TMIN     H           U

        Unknown
Year
2015 0      800
     1      800
     2      800
     3      800
     4      800
2016 14
     15
     16     800
     17
     18     800
2017 23
     24
     25     600
     26     600
     27

In [129]:
hot_df = fullframe.groupby('Year')['Value'].apply(lambda grp: grp.nlargest(5)).reset_index().drop('level_1' , axis = 1)
hot_result = pd.merge( hot_df, fullframe.loc[ fullframe.Attribute == 'TMAX',:] , left_on = ['Year','Value' ], right_on=['Year','Value'])
hot_result.groupby('Year').apply(lambda grp: grp.nlargest(5 , columns = 'Year'))

         Year  Value           St      Date Attribute Mflag Qflag Sflag  \
Year
2015 0   2015   55.6  USR0000HKAU  20150213      TMAX     H           U
     1   2015   55.6  USR0000HKAU  20150215      TMAX     H           U
     2   2015   55.6  USR0000HKAU  20150213      TMAX     H           U
     3   2015   55.6  USR0000HKAU  20150215      TMAX     H           U
     4   2015   53.9  USR0000HKAU  20150212      TMAX     H           U
2016 8   2016   53.9  USR0000CBEV  20160926      TMAX     H           U
     9   2016   52.8  USC00042319  20160729      TMAX                 7
     10  2016   52.2  USC00042319  20160620      TMAX                 7
     11  2016   52.2  USC00040924  20160621      TMAX                 7
     12  2016   52.2  USC00042319  20160727      TMAX                 7
2017 22  2017   52.8  USC00042319  20170620      TMAX                 7
     23  2017   52.8  USC00042319  20170624      TMAX                 7
     24  2017   52.8  USC00042319  20170707      TMAX                 7
     25  2017   52.8  USC00042319  20170801      TMAX                 7
     26  2017   52.8  USC00042319  20170620      TMAX                 7

        Unknown
Year
2015 0
     1
     2
     3
     4
2016 8
     9     2400
     10    2400
     11     800
     12    2400
2017 22    2400
     23    2400
     24    2400
     25    2400
     26    2400

## Hottest and coldest day and corresponding weather stations in the entire dataset

In [133]:
fullframe[fullframe.Value == fullframe.Value.max()]

                 St      Date Attribute  Value Mflag Qflag Sflag Unknown  Year
701130  USR0000HKAU  20150213      TMAX   55.6     H           U          2015
732864  USR0000HKAU  20150215      TMAX   55.6     H           U          2015

In [139]:
fullframe[fullframe.Value == fullframe.Value.min()]

                 St      Date Attribute  Value Mflag Qflag Sflag Unknown  Year
417070  USC00502339  20150127      TMIN  -52.8                 7     800  2015

## Median TMIN, TMAX for each year and corresponding weather stations

In [149]:
med_df = fullframe.groupby(['Year','Attribute']).Value.median().reset_index()
med_df

   Year Attribute  Value
0  2015      TMAX   19.4
1  2015      TMIN    6.1
2  2016      TMAX   19.4
3  2016      TMIN    5.6
4  2017      TMAX   19.2
5  2017      TMIN    5.6

In [155]:
result_max = pd.merge(med_df , fullframe.loc[ fullframe.Attribute == 'TMAX',:] , left_on = ['Year','Attribute','Value' ], right_on=['Year','Attribute','Value'])
result_min = pd.merge(med_df , fullframe.loc[ fullframe.Attribute == 'TMIN',:] , left_on = ['Year','Attribute','Value' ], right_on=['Year','Attribute','Value'])

In [161]:
result_max

       Year Attribute  Value           St      Date Mflag Qflag Sflag Unknown
0      2015      TMAX   19.4  USC00082944  20150101                 7     900
1      2015      TMAX   19.4  USR0000FSAN  20150101     H           U
2      2015      TMAX   19.4  USR0000HPTA  20150101     H           U
3      2015      TMAX   19.4  USC00089566  20150101                 7     730
4      2015      TMAX   19.4  USR0000HMLK  20150101     H           U
5      2015      TMAX   19.4  USR0000HKMO  20150101     H           U
6      2015      TMAX   19.4  USW00012832  20150101                 W
7      2015      TMAX   19.4  USC00088051  20150101                 7    2400
8      2015      TMAX   19.4  USR0000MMAR  20150102     H           U
9      2015      TMAX   19.4  USW00013833  20150102                 W    2400
10     2015      TMAX   19.4  USR0000TKIR  20150102     H           U
11     2015      TMAX   19.4  USC00087826  20150102                 7    1700
12     2015      TMAX   19.4  USW00013878  20150102                 W    2400
13     2015      TMAX   19.4  USW00013894  20150102                 W    2400
14     2015      TMAX   19.4  USW00053853  20150102                 W
15     2015      TMAX   19.4  USC00227840  20150102                 7    1600
16     2015      TMAX   19.4  USR0000GWAY  20150102     H           U
17     2015      TMAX   19.4  USW00063870  20150102                 W
18     2015      TMAX   19.4  USC00093465  20150102                 7    1300
19     2015      TMAX   19.4  USR0000GMID  20150102     H           U
20     2015      TMAX   19.4  USC00040790  20150102                 7    1500
21     2015      TMAX   19.4  USR0000GJON  20150102     H           U
22     2015      TMAX   19.4  USC00087025  20150102                 7    1400
23     2015      TMAX   19.4  USW00053848  20150102                 W
24     2015      TMAX   19.4  USW00093919  20150102                 W    2400
25     2015      TMAX   19.4  USR0000TSBS  20150103     H           U
26     2015      TMAX   19.4  USC00017020  20150103                 7    1700
27     2015      TMAX   19.4  USC00099502  20150103                 7     800
28     2015      TMAX   19.4  USR0000TANA  20150103     H           U
29     2015      TMAX   19.4  USC00165296  20150103                 7     800
...     ...       ...    ...          ...       ...   ...   ...   ...     ...
88169  2017      TMAX   19.2  USS0016E18S  20171028                 T
88170  2017      TMAX   19.2  USS0019L03S  20171029                 T
88171  2017      TMAX   19.2  USS0015H09S  20171029                 T
88172  2017      TMAX   19.2  USW00004125  20171029                 R
88173  2017      TMAX   19.2  USS0016H06S  20171029                 T
88174  2017      TMAX   19.2  USS0011R05S  20171029                 T
88175  2017      TMAX   19.2  USR0000MASS  20171031     H           U
88176  2017      TMAX   19.2  USW00063826  20171110                 R
88177  2017      TMAX   19.2  USW00053136  20171110                 R
88178  2017      TMAX   19.2  USW00053152  20171111                 R
88179  2017      TMAX   19.2  USW00063858  20171111                 R
88180  2017      TMAX   19.2  USW00063892  20171112                 R
88181  2017      TMAX   19.2  USW00063893  20171113                 R
88182  2017      TMAX   19.2  USW00063891  20171113                 R
88183  2017      TMAX   19.2  USW00023801  20171114                 R
88184  2017      TMAX   19.2  USW00073801  20171114                 R
88185  2017      TMAX   19.2  USW00003048  20171121                 R
88186  2017      TMAX   19.2  USS0007S04S  20171124                 T
88187  2017      TMAX   19.2  USW00063829  20171125                 R
88188  2017      TMAX   19.2  USS0009S11S  20171125                 T
88189  2017      TMAX   19.2  USW00063856  20171126                 R
88190  2017      TMAX   19.2  USW00023904  20171126                 R
88191  2017      TMAX   19.2  USW00053136  20171202                 R
88192  2017      TMAX   19.2  USW00063838  20171204                 R
88193  2017      TMAX   19.2  USW00023907  20171210                 R
88194  2017      TMAX   19.2  USW00053182  20171212                 R
88195  2017      TMAX   19.2  USW00073802  20171221                 R
88196  2017      TMAX   19.2  USW00092821  20171225                 R
88197  2017      TMAX   19.2  USW00003074  20171228                 R
88198  2017      TMAX   19.2  USS0011P02S  20171230                 T

[88199 rows x 9 columns]

In [162]:
result_min

        Year Attribute  Value           St      Date Mflag Qflag Sflag Unknown
0       2015      TMIN    6.1  USR0000CCOO  20150101     H           U
1       2015      TMIN    6.1  USW00013976  20150101                 W    2400
2       2015      TMIN    6.1  USC00163433  20150101                 7     800
3       2015      TMIN    6.1  USR0000LSAB  20150101     H           U
4       2015      TMIN    6.1  USR0000OREM  20150101     H           U
5       2015      TMIN    6.1  USC00099502  20150101                 7     800
6       2015      TMIN    6.1  USW00012926  20150101                 W
7       2015      TMIN    6.1  USC00012172  20150101                 7     800
8       2015      TMIN    6.1  USW00012975  20150101                 W
9       2015      TMIN    6.1  USR0000TBRA  20150101     H           U
10      2015      TMIN    6.1  USC00169376  20150101                 7     800
11      2015      TMIN    6.1  USW00023191  20150101                 W
12      2015      TMIN    6.1  USC00089566  20150101                 7     730
13      2015      TMIN    6.1  USC00096838  20150101                 7     900
14      2015      TMIN    6.1  USC00163313  20150101                 7    2400
15      2015      TMIN    6.1  USC00417170  20150101                 7    2400
16      2015      TMIN    6.1  USR0000GWAY  20150101     H           U
17      2015      TMIN    6.1  USC00418487  20150101                 7     800
18      2015      TMIN    6.1  USW00093841  20150101                 W
19      2015      TMIN    6.1  USC00410569  20150101                 7     800
20      2015      TMIN    6.1  USW00073805  20150101                 W
21      2015      TMIN    6.1  USC00414333  20150101                 7    2400
22      2015      TMIN    6.1  USR0000TMCF  20150101     H           U
23      2015      TMIN    6.1  USC00502227  20150101                 7     800
24      2015      TMIN    6.1  USR0000TMAT  20150101     H           U
25      2015      TMIN    6.1  USW00012972  20150101                 W    2400
26      2015      TMIN    6.1  USC00086842  20150101                 7     800
27      2015      TMIN    6.1  USW00012917  20150101                 W    2400
28      2015      TMIN    6.1  USW00053848  20150101                 W
29      2015      TMIN    6.1  USR0000TSBS  20150102     H           U
...      ...       ...    ...          ...       ...   ...   ...   ...     ...
142544  2017      TMIN    5.6  USR0000OCED  20171231     H           U
142545  2017      TMIN    5.6  USW00023277  20171231                 W
142546  2017      TMIN    5.6  USR0000AGOO  20171231     H           U
142547  2017      TMIN    5.6  USC00264480  20171231                 7     800
142548  2017      TMIN    5.6  USW00003192  20171231                 W
142549  2017      TMIN    5.6  USR0000CBGR  20171231     H           U
142550  2017      TMIN    5.6  USW00053139  20171231                 R
142551  2017      TMIN    5.6  USC00049785  20171231                 7    1600
142552  2017      TMIN    5.6  USC00415048  20171231                 7     800
142553  2017      TMIN    5.6  USC00412679  20171231                 7     700
142554  2017      TMIN    5.6  USR0000CHLR  20171231     H           U
142555  2017      TMIN    5.6  USC00024829  20171231                 7    1900
142556  2017      TMIN    5.6  USC00089401  20171231                 7     800
142557  2017      TMIN    5.6  USW00023244  20171231                 W
142558  2017      TMIN    5.6  USW00012895  20171231                 W
142559  2017      TMIN    5.6  USC00080228  20171231                 7     800
142560  2017      TMIN    5.6  USR0000CGSP  20171231     H           U
142561  2017      TMIN    5.6  USR0000AHUR  20171231     H           U
142562  2017      TMIN    5.6  USR0000ASOL  20171231     H           U
142563  2017      TMIN    5.6  USC00044405  20171231                 7     730
142564  2017      TMIN    5.6  USC00411542  20171231                 7     700
142565  2017      TMIN    5.6  USC00087205  20171231                 7    1600
142566  2017      TMIN    5.6  USC00043939  20171231                 7     800
142567  2017      TMIN    5.6  USW00023169  20171231                 W    2400
142568  2017      TMIN    5.6  USC00047880  20171231                 7    2400
142569  2017      TMIN    5.6  USR0000CMSA  20171231     H           U
142570  2017      TMIN    5.6  USR0000CDUN  20171231     H           U
142571  2017      TMIN    5.6  USC00046773  20171231                 7    1700
142572  2017      TMIN    5.6  USC00164700  20171231                 7     800
142573  2017      TMIN    5.6  USC00048917  20171231                 7    1500

[142574 rows x 9 columns]

## Median TMIN, TMAX for the entire dataset

In [164]:
fullframe.groupby(['Attribute'])['Value'].mean().reset_index()

  Attribute      Value
0      TMAX  17.756328
1      TMIN   5.371105